### ISSUE TITLE
大佬，请教一个bug

### ISSUE THREAD

**Issue by DreamerLuu** [yelusaleng/RRU-Net#42]
Traceback (most recent call last):
  File "D:/PyCharmProject/RRU-Net-master/train.py", line 148, in <module>
    train_net(net=net,
  File "D:/PyCharmProject/RRU-Net-master/train.py", line 65, in train_net
    imgs = np.array([i[0] for i in b]).astype(np.float32)
ValueError: could not broadcast input array from shape (3,256,256) into shape (3,)
 我用的casia微调，tam放的rgb（3*384*256）mask为（384*256）进入epoch时候debug看b为batch为6的列表每个元素0为（3*256*256）元素1为（256*256）请问这个bug问题出在哪里呢，我debug也没看懂

**Comment by yelusaleng** [comment]
mask的通道数要为1吧我记得

**Comment by DreamerLuu** [comment]
mask我放的都是灰度图呀

**Comment by DreamerLuu** [comment]
> mask的通道数要为1吧我记得

大佬 解决了谢谢，打扰了，这么久了还能回issue感谢

**Comment by yelusaleng** [comment]
不客气
---- 回复的原邮件 ----
发件人 ***@***.***> 日期 2024年11月12日 16:34 收件人 ***@***.***> 抄送至 ***@***.***>***@***.***> 主题 Re: [yelusaleng/RRU-Net] 大佬，请教一个bug (Issue #42) 
mask的通道数要为1吧我记得
大佬 解决了谢谢，打扰了，这么久了还能回issue感谢
